version: '3'
services:
  metabase-db:
    image: postgres:14
    container_name: metabase-db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metabase
    volumes:
      - metabase_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - metabase-network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - metabase-db
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: password
      MB_DB_HOST: metabase-db
    ports:
      - "3000:3000"
    networks:
      - metabase-network

networks:
  metabase-network:

volumes:
  metabase_data: