services:
  # Metabase's internal application database
  metabase-db:
    image: postgres:14
    container_name: metabase-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - metabase_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - metabase-network

  # Metabase application
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - metabase-db
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: ${MB_DB_HOST}
    ports:
      - "3000:3000"
    volumes:
      - ./plugins:/plugins
    networks:
      - metabase-network

  # ClickHouse data warehouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-meta
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "8124:8124"  # HTTP interface
      - "9001:9001"  # Native interface
    volumes:
      - metabase_clickhouse_data:/var/lib/clickhouse
    networks:
      - metabase-network

  # Mail testing service
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-meta
    ports:
      - "1026:1026"  # SMTP port
      - "8026:8026"  # Web UI port
    networks:
      - metabase-network

networks:
  metabase-network:

volumes:
  metabase_data:
  clickhouse_data:
  metabase_clickhouse_data:
