services:
  superset:
    image: apache/superset:latest
    container_name: superset
    restart: always
    environment:
      - SUPERSET_SECRET_KEY=6cddca5f0781d002c0c1425dc0bbbfe120e063894e351635bfd5a6bbaa31f87f
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - redis
      - clickhouse
    volumes:
      - superset_home:/app/superset_home
    networks:
      - superset_network
    command: >
      /bin/sh -c "superset db upgrade && 
                  superset init && 
                  superset run -h 0.0.0.0 -p 8088"

  postgres:
    image: postgres:14
    container_name: superset_postgres
    restart: always
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - superset_network

  redis:
    image: redis:latest
    container_name: superset_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - superset_network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"  # HTTP Interface
      - "9000:9000"  # Native TCP Interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-users.xml:/etc/clickhouse-server/users.d/clickhouse-users.xml
    networks:
      - superset_network
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ml8Cl54h
      CLICKHOUSE_DB: default

# Mail testing service
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - superset_network

networks:
  superset_network:
    driver: bridge

volumes:
  superset_home:
  postgres_data:
  clickhouse_data:
